---
# This file is in YAML format.
# The YAML specification can be found at https://yaml.org/spec/
# A gentle introduciton to YAML can be found at:
# https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started

# The chromatography type is determined is from the LCMS output file names.
# Aliases map alternative identifiers in the file name to the canonical name.
chromatography_types:
  - name: HILIC
    aliases:
      - HILICZ
      - Ag683775
  - name: C18
    aliases: []

# A Metatlas "workflow" contains:
#   1) A unique name consisting solely of letters, numbers, and dashes
#   2) A RT alignment step
#   3) Zero or more analysis steps
#
# Each RT alignment or analysis step contains an atlas definition.
# The atlas definition contains three fields:
#   1) name - name of the atlas as stored in the database
#   2) unique_id - unique_id field associated with the atlas in the database
#   3) do_alignment - if True, then the atlas should be copied and RT shifted to
#                     be in alignment with the experimental data.
#
# Each RT alignment or analysis step contains a set of parameters.
# These parameters are substituted into the RT_Alignment.ipynb
# or Targeted.ipynb notebook. Please see the notebook files for
# documentation of the parameters and their values:
# https://github.com/biorack/metatlas/blob/main/notebooks/reference/RT_Alignment.ipynb
# https://github.com/biorack/metatlas/blob/main/notebooks/reference/Targeted.ipynb

workflows:
  - name: JGI-HILIC
    rt_alignment:
        atlas:
          name: HILICz150_ANT20190824_TPL_QCv3_Unlab_POS
          unique_id: e7fba1813272439498405436a28b90b2
        parameters:
          groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
          include_groups: ["QC"]
          exclude_groups: ["NEG"]
          use_poly_model: True
          google_folder: 0B-ZDcHbPi-aqZzE5V3hOZFc0dms
    analyses:
        - name: QC-POS
          atlas:
            name: HILICz150_ANT20190824_TPL_QCv3_Unlab_POS
            unique_id: e7fba1813272439498405436a28b90b2
          parameters:
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            include_groups: ["QC"]
            exclude_groups: ["NEG"]
            generate_qc_outputs: True
        - name: ISTDsEtc-POS
          atlas:
            name: HILICz150_ANT20190824_TPL_IS_LabUnlab2_POS
            unique_id: c6db576b879043768125c4e03e6a8f6e
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "NEG", "FPS"]
            exclude_groups_for_outputs: ["QC", "NEG", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            generate_qc_outputs: True
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: EMA-POS
          atlas:
            name: HILICz150_ANT20190824_TPL_EMA_Unlab_POS
            unique_id: 89694aa326cd46958d38d8e9066de16c
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "NEG", "FPS"]
            exclude_groups_for_outputs: ["QC", "NEG", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            require_all_evaluated: True
            filter_removed: True
            num_points: 5
            peak_height: 4e5
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: QC-NEG
          atlas:
            name: HILICz150_ANT20190824_TPL_QCv3_Unlab_NEG
            unique_id: 5b77242ad9c04e76a745e51e9d6a3c4b
          parameters:
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            include_groups: ["QC"]
            exclude_groups: ["POS"]
            generate_qc_outputs: True
        - name: ISTDsEtc-NEG
          atlas:
            name: HILICz150_ANT20190824_TPL_IS_LabUnlab2_NEG
            unique_id: e299c951fc8b48ea82524a6c9615f418
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "POS", "FPS"]
            exclude_groups_for_outputs: ["QC", "POS", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            generate_qc_outputs: True
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: EMA-NEG
          atlas:
            name: HILICz150_ANT20190824_TPL_EMA_Unlab_NEG
            unique_id: a5f7bc81caa94853bbd6ee4b44e09187
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "POS", "FPS"]
            exclude_groups_for_outputs: ["QC", "POS", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            require_all_evaluated: True
            filter_removed: True
            num_points: 5
            peak_height: 4e5
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
  - name: JGI-C18
    rt_alignment:
        atlas:
          name: C18_20220215_TPL_IS_Unlab_POS
          unique_id: 322ed4c5fabe49349bcbc2857fbcd0dc
        parameters:
          groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
          include_groups: ["QC"]
          exclude_groups: ["NEG"]
          use_poly_model: True
          google_folder: 0B-ZDcHbPi-aqZzE5V3hOZFc0dms
    analyses:
        - name: QC-POS
          atlas:
            name: C18_20220215_TPL_IS_Unlab_POS
            unique_id: 322ed4c5fabe49349bcbc2857fbcd0dc
          parameters:
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            include_groups: ["QC"]
            exclude_groups: ["NEG"]
            generate_qc_outputs: True
        - name: ISTDsEtc-POS
          atlas:
            name: C18_20220215_TPL_IS_Unlab_POS
            unique_id: 322ed4c5fabe49349bcbc2857fbcd0dc
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "NEG", "FPS"]
            exclude_groups_for_outputs: ["QC", "NEG", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            generate_qc_outputs: True
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: EMA-POS
          atlas:
            name: C18_20220531_TPL_EMA_Unlab_POS
            unique_id: 669b750765634159a7f16645e6cf7758
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: positive
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "NEG", "FPS"]
            exclude_groups_for_outputs: ["QC", "NEG", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            require_all_evaluated: True
            filter_removed: True
            num_points: 3
            peak_height: 1e6
            msms_score: 0.6
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: QC-NEG
          atlas:
            name: C18_20220215_TPL_IS_Unlab_NEG
            unique_id: db58154082824230be4f7fee93e4ebd9
          parameters:
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            include_groups: ["QC"]
            exclude_groups: ["POS"]
            generate_qc_outputs: True
        - name: ISTDsEtc-NEG
          atlas:
            name: C18_20220215_TPL_IS_Unlab_NEG
            unique_id: db58154082824230be4f7fee93e4ebd9
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "POS", "FPS"]
            exclude_groups_for_outputs: ["QC", "POS", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            generate_qc_outputs: True
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
        - name: EMA-NEG
          atlas:
            name: C18_20220531_TPL_EMA_Unlab_NEG
            unique_id: 19b4c10e304246cbbbe5fd3574770e5d
            do_alignment: True
          parameters:
            copy_atlas: True
            polarity: negative
            groups_controlled_vocab: ["QC", "InjBl", "ISTD"]
            exclude_groups: ["QC", "POS", "FPS"]
            exclude_groups_for_outputs: ["QC", "POS", "FPS"]
            exclude_lcmsruns_in_output_chromatograms: ["InjBl", "QC", "Blank", "blank"]
            require_all_evaluated: True
            filter_removed: True
            num_points: 3
            peak_height: 1e6
            msms_score: 0.6
            generate_analysis_outputs: True
            msms_refs: /global/cfs/cdirs/metatlas/projects/spectral_libraries/msms_refs_v3.tab
