[tool.black]
line-length = 110

[tool.pylint.messages_control]
# first two are for black compatibility
# duplicate-code cannot be disabled on per file/block/line
#                https://github.com/PyCQA/pylint/issues/214
disable = "bad-continuation, bad-whitespace, duplicate-code"

[tool.pylint.format]
max-line-length = "110"

[tool.pylint.TYPECHECK]
generated-members = "pandas.*"

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning:dataset.*:"
