[tool.black]
line-length = 110

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "110"

[tool.pylint.TYPECHECK]
generated-members = "pandas.*"

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning:dataset.*:"
