apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metatlas-atlasdb
  labels:
    app: metatlas
spec:
  serviceName: metatlas-atlasdb
  selector:
    matchLabels:
      app: metatlas
      tier: db
  template:
    metadata:
      labels:
        app: metatlas
        tier: db
    spec:
      containers:
        - name: atlasdb
          image: "{{ .Values.dbImage }}"
          imagePullPolicy: "{{ .Values.imageConfig.pullPolicy }}"
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypw
          ports:
          - containerPort: 3306
            name: mysql
