include_polarities:
  - POS
  - NEG
include_chromatographies:
  - C18
  - HILIC
include_adducts:
  - "[M+H]+"
  - "[M+Na]+"
  - "[M-H2O+H]+"
  - "[M+K]+"
  - "[M+NH4]+"
  - "[M]+"
  - "[M+2H]2+"
  - "[M-H]-"
  - "[M+Cl]-"
  - "[M]-"
  - "[M-2H]2-"
ppm_tolerance: 5
standards_output_path: "/global/homes/b/bkieft/metabolomics_standards_annotation/standard_library_annotation/schellermetasci"
standards_input_file: "/global/homes/b/bkieft/metabolomics_standards_annotation/standard_library_annotation/schellermetasci/scheller_test.csv"
current_ema_atlases:
  HILICZ:
    positive: "/global/homes/b/bkieft/metatlas-data/HILIC/HILIC_EMA-standards_positive.tsv"
    negative: "/global/homes/b/bkieft/metatlas-data/HILIC/HILIC_EMA-standards_negative.tsv"
  C18:
    positive: "/global/homes/b/bkieft/metatlas-data/C18/C18_EMA-standards_positive.tsv"
    negative: "/global/homes/b/bkieft/metatlas-data/C18/C18_EMA-standards_negative.tsv"
current_qc_atlases:
  HILICZ: "/global/homes/b/bkieft/metatlas-data/HILIC/HILIC_QCv7_positive.tsv"
  C18: "/global/homes/b/bkieft/metatlas-data/C18/C18_QCv7_positive.tsv"
direct_deposit_new_emas: false
direct_store_to_compounds_table: false
current_msms_refs_path: "/global/cfs/cdirs/metatlas/projects/spectral_libraries/20240430_istdv7-addition_msms_refs.tab"
msms_refs_metadata:
  ce_type: "ramp"
  msms_refs_prefix: "schellermetasci"
  frag_method: "HCD"
  instrument_type: "Orbitrap"
  decimal: 4.0
raw_data_from_cache: true
selected_data_from_cache: true
filtered_data_from_cache: true
ema_atlas_data_from_cache: false
rt_correction_data_from_cache: false
msms_refs_data_from_cache: false