FROM python:3.8-slim-buster

# https://portal.nersc.gov/cfs/m2650/metatlas/test_data
# serves from /global/cfs/cdirs/m2650/www/metatlas/test_data
ARG BASE_DATA_URL=https://portal.nersc.gov/cfs/m2650/metatlas/test_data/ci02
ARG REFS_DIR=/global/project/projectdirs/metatlas/projects/spectral_libraries
ARG H5_DIR=/project/projectdirs/metatlas/raw_data/akuftin/20201106_JGI-AK_PS-KM_505892_OakGall_final_QE-HF_HILICZ_USHXG01583

ENV METATLAS_LOCAL=True

EXPOSE 8888

RUN apt-get update && apt-get install -y libxrender1 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /io /src /work $REFS_DIR $H5_DIR
ADD $BASE_DATA_URL/20201106_JGI-AK_PS-KM_505892_OakGall_final_QE-HF_HILICZ_USHXG01583_POS_MSMS_0_QC_Pre_Rg70to1050-CE102040--QC_Run7.h5 $H5_DIR/
ADD $BASE_DATA_URL/20201106_JGI-AK_PS-KM_505892_OakGall_final_QE-HF_HILICZ_USHXG01583_POS_MSMS_0_QC_Post_Rg70to1050-CE102040--QC_Run308.h5 $H5_DIR/

COPY requirements.txt /requirements.txt
RUN pip install --quiet -r requirements.txt

ADD $BASE_DATA_URL/meta_atlas_rt_predict.sqlite3 /work/root_workspace.db

WORKDIR /work

CMD ["/usr/local/bin/jupyter", "nbclassic", "--ip=0.0.0.0", "--allow-root", "--ServerApp.token=''", "--ServerApp.root_dir=/"]
