name: cd
on:
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:

jobs:
  build_push_docker_image:
    name: Build and push metatlas_shifter docker image
    if: github.repository == 'biorack/metatlas' && (github.event.pull_request.merged || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: wjhjgi
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: generate version_info file
      run: python ./most_recent_commits.py > docker/.version_info
    - name: generate time based tag
      id: timestamp
      run: |
        DATE_TIME=$(date -u +"%Y%m%d_%H%M%S")
        echo "::set-output name=date_time::${DATE_TIME}"
    - name: Build Docker images
      id: build
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./docker
        file: ./docker/Dockerfile.shifter
        platforms: linux/amd64
        cache-from: type=registry,ref=wjhjgi/metatlas_shifter:latest
        cache-to: type=inline
        tags: |
          wjhjgi/metatlas_shifter:${{ steps.timestamp.outputs.date_time }}
          wjhjgi/metatlas_shifter:latest
          doejgi/metatlas_shifter:${{ steps.timestamp.outputs.date_time }}
          doejgi/metatlas_shifter:latest
        push: true
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
