name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: Run unit tests suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Cache nox environment for unit tests
      uses: actions/cache@v2
      with:
        path: ~/work/metatlas/metatlas/.nox
        key: ${{ runner.os }}-nox
    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0
    - name: Run unit tests
      run: nox -s unit_tests-3.8
  system_test1:
    name: Run system test 1 - HILIC targeted
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_targeted
  system_test2:
    name: Run system test 2 - RT prediction
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_rt_predict
  system_test3:
    name: Run system test 3 - add MSMS references
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_add_msms_ref
  system_test4:
    name: Run system test 4 - C18 targeted
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_c18
