name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: Run unit tests suite
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Cache nox environment for unit tests
      uses: actions/cache@v3
      with:
        path: ~/work/metatlas/metatlas/.nox
        key: ${{ runner.os }}-nox
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run unit tests
      run: nox -s unit_tests-3.8
  system_test1:
    name: Run system test 1 - HILIC targeted
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Run system tests
      run: |
        set -x
        pwd
        ls -la
        ls -la /home/runner/work/metatlas/metatlas
        git rev-parse HEAD
        docker run --rm -u 0:0 -v "$(pwd):/src" docker.io/doejgi/metatlas_ci:1.1.0 python -c 'from metatlas.tools.environment import repo_dir; print(repo_dir())'
        docker run --rm -u 0:0 -v "$(pwd):/src" docker.io/doejgi/metatlas_ci:1.1.0 python -c 'from metatlas.tools.environment import repo_dir; import subprocess; subprocess.run(["git", "rev-parse", "HEAD"], cwd=repo_dir())'
        docker run --rm -u 0:0 -v "$(pwd):/src" docker.io/doejgi/metatlas_ci:1.1.0 python -c 'from metatlas.tools.environment import get_repo_hash; print(get_repo_hash())'
        # pip install nox
        #nox -s system_tests-3.8 -- -k test_targeted
