name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  unit_tests:
    name: Run unit tests suite
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Cache nox environment for unit tests
      uses: actions/cache@v3
      with:
        path: ~/work/metatlas/metatlas/.nox
        key: ${{ runner.os }}-nox
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run unit tests
      run: nox -s unit_tests-3.8
  system_test1:
    name: Run system test 1 - HILIC targeted
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_targeted
  system_test2:
    name: Run system test 2 - RT alignment
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_rt_alignment
  system_test3:
    name: Run system test 3 - add MSMS references
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_add_msms_ref
  system_test4:
    name: Run system test 4 - C18 targeted
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_c18
  system_test5:
    name: Run system test 5 - HILIC Targeted_hybrid
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup nox
      uses: daisylb/setup-nox@c375841575e07f30359a5843bf0bffa7aa596782
    - name: Run system tests
      run: nox -s system_tests-3.8 -- -k test_hybrid
