name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Cache nox environment for unit tests
        uses: actions/cache@v2
        with:
          path: ~/work/metatlas/metatlas/.nox
          key: ${{ runner.os }}-nox
      - name: Setup nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: Run unit tests
        run: nox -s unit_tests-3.8
      - name: Run system tests
        run: nox -s system_tests-3.8
