name: ci_cd
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Cache nox environment for unit tests
        uses: actions/cache@v2
        with:
          path: ~/work/metatlas/metatlas/.nox
          key: ${{ runner.os }}-nox
      - name: Setup nox
        uses: excitedleigh/setup-nox@v2.0.0
      - name: Run unit tests
        run: nox -s unit_tests-3.8
      - name: Run system tests
        run: nox -s system_tests-3.8
  build_docker_image:
    name: Build metatlas_shifter docker image
    if: github.repository == 'biorack/metatlas'
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker images
      id: build
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./docker
        file: ./docker/Dockerfile.shifter
        platforms: linux/amd64
        tags: wjhjgi/metatlas_shifter:latest
  push_docker_image:
    name: Push metatlas_shifter docker image
    needs: test
    if: github.repository == 'biorack/metatlas'
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: wjhjgi
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      id: push
      uses: docker/build-push-action@v2.7.0
      with:
        context: ./docker
        file: ./docker/Dockerfile.shifter
        platforms: linux/amd64
        push: true
        tags: wjhjgi/metatlas_shifter:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
